export default {
  "1": "Just begun",
  "2": "One Little Duck",
  "3": "Cup of Tea",
  "4": "Knock at the Door",
  "5": "Man Alive",
  "6": "Chopsticks",
  "7": "Hope in heaven",
  "8": "One Fat Lady",
  "10": "Big Ben",
  "11": "Legs Eleven",
  "13": "Unlucky for Some",
  "16": "Sweet Sixteen",
  "17": "Never been kissed",
  "21": "Key of the Door",
  "22": "Two Little Ducks",
  "23": "Thee and Me",
  "24": "Two Dozen",
  "26": "Pick and Mix",
  "32": "Halfway There",
  "33": "Come in For Your Tea",
  "37": "More Than Eleven",
  "38": "You’re Late",
  "39": "All the steps",
  "40": "Over the Hill",
  "44": "All the fours",
  "50": "Bulls eye",
  "51": "Tweak of the Thumb",
  "55": "All the Fives",
  "57": "Heinz Varieties",
  "64": "knock on the door",
  "66": "Clickety-Click",
  "71": "Bang on the Drum",
  "72": "In for a Poo",
};